//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3603
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NU.OJL.MPRTOS.TLV.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NU.OJL.MPRTOS.TLV.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap atr2atr {
            get {
                object obj = ResourceManager.GetObject("atr2atr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap atr2bhr {
            get {
                object obj = ResourceManager.GetObject("atr2bhr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap attribute {
            get {
                object obj = ResourceManager.GetObject("attribute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BackwardArrow {
            get {
                object obj = ResourceManager.GetObject("BackwardArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap behavior {
            get {
                object obj = ResourceManager.GetObject("behavior", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bhr2atr {
            get {
                object obj = ResourceManager.GetObject("bhr2atr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bhr2bhr {
            get {
                object obj = ResourceManager.GetObject("bhr2bhr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   cnv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConvertRuleFileExtension {
            get {
                return ResourceManager.GetString("ConvertRuleFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   convertRules に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultConvertRulesDirectoryName {
            get {
                return ResourceManager.GetString("DefaultConvertRulesDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   resourceHeaders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultResourceHeadersDirectoryName {
            get {
                return ResourceManager.GetString("DefaultResourceHeadersDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TraceLogVisualizer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultTemporaryDirectoryName {
            get {
                return ResourceManager.GetString("DefaultTemporaryDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   visualizeRules に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultVisualizeRulesDirectoryName {
            get {
                return ResourceManager.GetString("DefaultVisualizeRulesDirectoryName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Eraser {
            get {
                object obj = ResourceManager.GetObject("Eraser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ForwardArrow {
            get {
                object obj = ResourceManager.GetObject("ForwardArrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ForwardArrow1 {
            get {
                object obj = ResourceManager.GetObject("ForwardArrow1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon hand {
            get {
                object obj = ResourceManager.GetObject("hand", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon handHold {
            get {
                object obj = ResourceManager.GetObject("handHold", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap resource {
            get {
                object obj = ResourceManager.GetObject("resource", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   res に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ResourceFileExtension {
            get {
                return ResourceManager.GetString("ResourceFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   resh に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ResourceHeaderFileExtension {
            get {
                return ResourceManager.GetString("ResourceHeaderFileExtension", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap resources {
            get {
                object obj = ResourceManager.GetObject("resources", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SearchWhole {
            get {
                object obj = ResourceManager.GetObject("SearchWhole", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SearchWhole1 {
            get {
                object obj = ResourceManager.GetObject("SearchWhole1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingFileExtension {
            get {
                return ResourceManager.GetString("SettingFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   tlv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StandardFormatTraceLogFileExtension {
            get {
                return ResourceManager.GetString("StandardFormatTraceLogFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TraceLogFileExtension {
            get {
                return ResourceManager.GetString("TraceLogFileExtension", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap visualize {
            get {
                object obj = ResourceManager.GetObject("visualize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   viz に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VisualizeRuleFileExtension {
            get {
                return ResourceManager.GetString("VisualizeRuleFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   shp に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VisualizeShapesFileExtension {
            get {
                return ResourceManager.GetString("VisualizeShapesFileExtension", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon zoomer {
            get {
                object obj = ResourceManager.GetObject("zoomer", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon zoomerIn {
            get {
                object obj = ResourceManager.GetObject("zoomerIn", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon zoomerOut {
            get {
                object obj = ResourceManager.GetObject("zoomerOut", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon zoomSelect {
            get {
                object obj = ResourceManager.GetObject("zoomSelect", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
