//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.1433
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NU.OJL.MPRTOS.TLV.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NU.OJL.MPRTOS.TLV.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   tlv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CommonFormatTraceLogFileExtension {
            get {
                return ResourceManager.GetString("CommonFormatTraceLogFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   cnv に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConvertRuleFileExtension {
            get {
                return ResourceManager.GetString("ConvertRuleFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   convertRules に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultConvertRulesDirectoryName {
            get {
                return ResourceManager.GetString("DefaultConvertRulesDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   resourceHeaders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultResourceHeadersDirectoryName {
            get {
                return ResourceManager.GetString("DefaultResourceHeadersDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   visualizeRules に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultVisualizeRulesDirectoryName {
            get {
                return ResourceManager.GetString("DefaultVisualizeRulesDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   res に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ResourceFileExtension {
            get {
                return ResourceManager.GetString("ResourceFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   resh に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ResourceHeaderFileExtension {
            get {
                return ResourceManager.GetString("ResourceHeaderFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   setting.json に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingFileName {
            get {
                return ResourceManager.GetString("SettingFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   log に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TraceLogFileExtension {
            get {
                return ResourceManager.GetString("TraceLogFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   viz に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VisualizeRuleFileExtension {
            get {
                return ResourceManager.GetString("VisualizeRuleFileExtension", resourceCulture);
            }
        }
    }
}
